_wandb:
    value:
        cli_version: 0.24.0
        e:
            gizie0apmlxb1hnm6mgvlb2212up5nzx:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "198303674368"
                        used: "11479171072"
                email: mattia.rosso@kaust.edu.sa
                executable: /ibex/user/rossom/conda-environments/chemprop/bin/python3
                git:
                    commit: da544b14bd9c95b3e74f0aff11b7cd794e235a26
                    remote: git@github.com:mattyred/nf10k.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-46a51200-704e-a12a-a307-1eb7f78fe805
                host: gpu502-01
                memory:
                    total: "404336300032"
                os: Linux-5.14.0-427.20.1.el9_4.0.1.x86_64-x86_64-with-glibc2.34
                program: /ibex/user/rossom/nf10k/train.py
                python: CPython 3.11.14
                root: .
                slurm:
                    cluster_name: dragon
                    conf: /opt/slurm/cluster/ibex/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00070000
                    cpu_bind_list: "0x00070000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "3"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: pi-filippm
                    job_cpus_per_node: "3"
                    job_end_time: "1769060951"
                    job_gid: "1212516"
                    job_group: g-rossom
                    job_id: "44035123"
                    job_name: bash
                    job_nodelist: gpu502-01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1769017751"
                    job_uid: "212516"
                    job_user: rossom
                    jobid: "44035123"
                    launch_node_ipaddr: 10.109.65.170
                    localid: "0"
                    mem_per_node: "131072"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu502-01
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "40253"
                    pty_win_col: "154"
                    pty_win_row: "22"
                    script_context: prolog_task
                    srun_comm_host: 10.109.65.170
                    srun_comm_port: "35231"
                    step_gpus: "4"
                    step_id: "0"
                    step_launcher_port: "35231"
                    step_nodelist: gpu502-01
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: "12894"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /ibex/user/rossom/nf10k
                    submit_host: vsc509-29-r
                    task_pid: "2801922"
                    tasks_per_node: "1"
                    topology_addr: main-intel.ibsw-intel-05-2.gpu502-01
                    topology_addr_pattern: switch.switch.node
                    umask: "0022"
                startedAt: "2026-01-21T18:21:06.404002Z"
                writerId: gizie0apmlxb1hnm6mgvlb2212up5nzx
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
                - 106
            "2":
                - 1
                - 5
                - 53
                - 106
            "3":
                - 7
                - 66
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_norm:
    value:
        - RMSE(task_weights=[[1.0]])
        - MSE(task_weights=[[1.0]])
        - R2Score()
final_lr:
    value: 0.0001
init_lr:
    value: 0.0001
max_lr:
    value: 0.001
metrics:
    value: null
warmup_epochs:
    value: 2
